### ISSUE TITLE
seeing lots of errors: gendata: hGetBuf: invalid argument (Invalid argument)

### ISSUE THREAD

**Issue by aeyakovenko** [acid-state/acid-state#69] opened 2016-01-26 19:58 UTC
seeing lots of errors:

```
gendata: dist/db/events-0000000330.log: hGetBuf: invalid argument (Invalid argument)
```

i am trying to download a bunch of and store it as an IxSet in the database, but I regularly see this error during program start.

So I dont think its due to the 2gb limit, here are some callstacks from the profiler

```
*** Exception (reporting due to +RTS -xc): (THUNK_1_1), stack trace:                      
  FileIO.readLock,                                                                        
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK_1_1), stack trace:                      
  FileIO.readLock,                                                                        
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK_2_0), stack trace:                      
  FileIO.readLock,                                                                        
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK), stack trace:                          
  FileIO.breakLock,                                                                       
  called from FileIO.maybeBreakLock,                                                      
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK), stack trace:                          
  FileIO.breakLock,                                                                       
  called from FileIO.maybeBreakLock,                                                      
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata
*** Exception (reporting due to +RTS -xc): (THUNK_1_1), stack trace:                      
  FileIO.readLock,                                                                        
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK_1_1), stack trace:                      
  FileIO.readLock,                                                                        
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK_2_0), stack trace:                      
  FileIO.readLock,                                                                        
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK), stack trace:                          
  FileIO.breakLock,                                                                       
  called from FileIO.maybeBreakLock,                                                      
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata                                                             
*** Exception (reporting due to +RTS -xc): (THUNK), stack trace:                          
  FileIO.breakLock,                                                                       
  called from FileIO.maybeBreakLock,                                                      
  called from FileIO.checkLock,                                                           
  called from FileIO.obtainPrefixLock,                                                    
  called from Data.Acid.Local.resumeLocalStateFrom,                                       
  called from Data.Acid.Local.openLocalStateFrom,                                         
  called from Util.DB.new,                                                                
  called from GenData.gendata 
```

the lock handle is getting closed maybe?

**Comment by aeyakovenko** [comment] 2016-01-29 01:35
Seems like acid breaks on OSX with files over 2gb.  Is something tracking the size of the file with an Int? Int is a 32bit singed on LP64.

**Comment by stepcut** [comment] 2016-05-31 13:57
What OS are you using? Do you think pull request #40 is related?

**Comment by dmjio** [comment] 2016-06-01 19:23
@aeyakovenko Can you show your code? At first glance it looks like you're trying to open your state on every single insert.

**Comment by adamgundry** [comment] 2018-08-15 15:36
I'm guessing this is something to do with locking, which changed significantly with #91. In the absence of a reproduction case I propose we simply close this. Feel free to reopen if you disagree.

**Closed by adamgundry** 2018-08-15 15:36 UTC
